name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install  # Replace with your package manager and dependencies if needed

    - name: Validate HTML and CSS
      run: |
        # Validate HTML using HTMLHint
        npm install -g htmlhint
        htmlhint ./*.html  # Replace with your HTML files' location
        
        # Validate CSS using Stylelint
        npm install -g stylelint stylelint-config-standard
        stylelint ./*.css  # Replace with your CSS files' location

    - name: Build
      run: |
        npm run build

    - name: Deploy to GitHub Pages
      run: |
        # Deploy to GitHub Pages
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout main
        git add .
        git commit -m "Auto-deploy to GitHub Pages"
        git push -f origin main
